# Generated by Django 3.2.8 on 2021-10-19 04:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('name', models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=120, null=True)),
                ('shipping_address', models.CharField(choices=[('billing', 'Billing address'), ('shipping', 'Shipping address')], max_length=120, primary_key=True, serialize=False)),
                ('billing_address', models.CharField(choices=[('billing', 'Billing address'), ('shipping', 'Shipping address')], max_length=120)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='United States of America', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=False, max_length=50)),
                ('category_description', models.TextField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_firstname', models.CharField(max_length=50)),
                ('cust_lastname', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=False, max_length=120)),
                ('product_description', models.TextField(default=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('product_category', models.CharField(default=False, max_length=120)),
                ('product_catalog', models.CharField(default=False, max_length=120)),
                ('remaining_quantity', models.IntegerField(default=1000)),
                ('category_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Credit card', 'credit card'), ('Debit card', 'Debit card')], max_length=120)),
                ('payment_status', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=120)),
                ('order_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(default=False, max_length=120, primary_key=True, serialize=False)),
                ('shipping_address_final', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5.99, max_digits=100)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('active', models.BooleanField(default=True)),
                ('date_placed', models.DateTimeField(auto_now=True)),
                ('date_shipped', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.customer')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.payment')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.addresses')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart_total', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.product')),
            ],
        ),
    ]
