# Generated by Django 3.2.7 on 2021-12-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_catalog',
        ),
    ]
