# Generated by Django 3.2.7 on 2021-12-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0002_auto_20211205_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
