# Generated by Django 3.2.8 on 2021-10-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0002_rename_shipping_address_final_orders_billing_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
    ]
