# Generated by Django 3.2.7 on 2021-11-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_lastname',
        ),
    ]
