# Generated by Django 3.2.8 on 2021-10-19 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0003_rename_addresses_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('name', models.CharField(blank=True, help_text='Shipping to? Who is it for?', max_length=120, null=True)),
                ('shipping_Addresses', models.CharField(choices=[('billing', 'Billing Addresses'), ('shipping', 'Shipping Addresses')], max_length=120, primary_key=True, serialize=False)),
                ('billing_Addresses', models.CharField(choices=[('billing', 'Billing Addresses'), ('shipping', 'Shipping Addresses')], max_length=120)),
                ('Addresses_line_1', models.CharField(max_length=120)),
                ('Addresses_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='United States of America', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='orders',
            name='billing_Addresses',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_Addresses',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.addresses'),
        ),
    ]
