# Generated by Django 3.2.7 on 2021-11-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0003_auto_20211117_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
