# Generated by Django 3.2.7 on 2021-10-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0004_auto_20211019_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='billing_Addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Sandaapp.customer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Sandaapp.payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_Addresses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Sandaapp.addresses'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Sandaapp.category'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sandaapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_catalog',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
