# Generated by Django 3.2.8 on 2021-12-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0004_product_image'),
        ('Sandaapp', '0005_auto_20211117_2235'),
    ]

    operations = [
    ]
