# Generated by Django 3.2.8 on 2021-10-27 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0005_auto_20211019_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipping_Addresses',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
