# Generated by Django 4.0 on 2021-12-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sandaapp', '0006_merge_0004_product_image_0005_auto_20211117_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
